package hr.algebra.sevenwonders.model;

public enum WonderType {
    GREAT_PYRAMID_OF_GIZA, COLOSSUS_OF_RHODES, LIGHTHOUSE_OF_ALEXANDRIA, MAUSOLEUM_AT_HALICARNASSUS, TEMPLE_OF_ARTEMIS, STATUE_OF_ZEUS, HANGING_GARDENS
}
